### ISSUE TITLE
Substring Levenshtein

### ISSUE THREAD

**Issue by gr33ndata** [lanl/pyxDamerauLevenshtein#2]
Is it possible to add a method, so when given substring a, string b, and a maximum normalized edit distance value; the method returns indexes for all occurrences of a in b, where the normalized Levenshtein is lower or equal to the given maximum edit distance value.

**Comment by sergiocorreia** [comment]
Hi Geoffrey,

There is a very useful use case for this option: implementing Peter Norvig's [spellchecker](http://norvig.com/spell-correct.html)

His `edits()` and `edits2()` functions return all the words within a distance of 1-2 in the Damerau-Levenshtein metric. The problem is that they are quite slow as they are implemented in pure Python (right now they are taking 90% of the time in a script I've been running for several hours)

Cheers,
Sergio

**Comment by gfairchild** [comment]
Good suggestion.
